### ISSUE TITLE
Equiping quantum chestplate from Modern Industrialization crashes the client only mentioning AllArmor mod.

### ISSUE THREAD

**Issue by frikinjay** [CyborgCabbage/OopsAllArmor#3]
When you try to equip a quantum chestplate from Modern Industrialization by right clicking the chestplate while in main hand the game crashes with this report.
```
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1856.method_8105()" because "ingredient" is null
	at net.minecraft.class_1391.handler$zgi000$injected(cyborgcabbage/allarmor/mixin/TemptWithArmorMixin.java [allarmor.mixins.json]:28)
	at net.minecraft.class_1391.method_6312(class_1391.java)
	at net.minecraft.class_4051.method_18419(class_4051.java:69)
	at net.minecraft.class_1924.method_18468(class_1924.java:144)
	at net.minecraft.class_1924.method_18462(class_1924.java:121)
	at net.minecraft.class_1391.method_6264(class_1391.java:45)
	at net.minecraft.class_4135.method_6264(class_4135.java:22)
	at net.minecraft.class_1355.method_6275(class_1355.java:98)
	at net.minecraft.class_1308.method_6023(class_1308.java:741)
	at net.minecraft.class_1309.method_6007(class_1309.java:2604)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at dev.itsmeow.betteranimalsplus.common.entity.EntityGoose.method_6007(EntityGoose.java:154)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1391.handler$zgi000$injected(cyborgcabbage/allarmor/mixin/TemptWithArmorMixin.java [allarmor.mixins.json]:28)
	at net.minecraft.class_1391.method_6312(class_1391.java)
	at net.minecraft.class_4051.method_18419(class_4051.java:69)
	at net.minecraft.class_1924.method_18468(class_1924.java:144)
	at net.minecraft.class_1924.method_18462(class_1924.java:121)
	at net.minecraft.class_1391.method_6264(class_1391.java:45)
	at net.minecraft.class_4135.method_6264(class_4135.java:22)
	at net.minecraft.class_1355.method_6275(class_1355.java:98)
	at net.minecraft.class_1308.method_6023(class_1308.java:741)
	at net.minecraft.class_1309.method_6007(class_1309.java:2604)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at dev.itsmeow.betteranimalsplus.common.entity.EntityGoose.method_6007(EntityGoose.java:154)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)

-- Entity being ticked --
Details:
	Entity Type: betteranimalsplus:goose (dev.itsmeow.betteranimalsplus.common.entity.EntityGoose)
	Entity ID: 338
	Entity Name: Goose
	Entity's Exact location: 27.00, 62.63, 233.00
	Entity's Block location: World: (27,62,233), Section: (at 11,14,9 in 1,3,14; chunk contains blocks 16,-64,224 to 31,319,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.02, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['frikinjay'/380, l='ServerLevel[New World]', x=45461.35, y=67.00, z=48034.49]]
	Chunk stats: 4610
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,73,256), Section: (at 0,9,0 in -2,4,16; chunk contains blocks -32,-64,256 to -17,319,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 426115 game time, 84090 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 10598 (now: true), thunder time: 11765 (now: true)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by CyborgCabbage** [comment]
This bug should be fixed in 1.1.3, thank you for posting a bug report.
