### ISSUE TITLE
Random crash while wearing bow armor leggings. 

### ISSUE THREAD

**Issue by frikinjay** [CyborgCabbage/OopsAllArmor#4]
```
Description: Watching Server

java.lang.Error: Watchdog
	at cyborgcabbage.allarmor.item.ArmorSet.damage(ArmorSet.java:145)
	at net.minecraft.class_1309.handler$zeh000$injected(moriyashiine/bewitchment/mixin/familiar/LivingEntityMixin.java [bewitchment.mixins.json]:239)
	at net.minecraft.class_1309.method_5643(class_1309.java)
	at net.minecraft.class_1657.method_5643(class_1657.java:914)
	at net.minecraft.class_3222.method_5643(class_3222.java:705)
	at net.minecraft.class_1665.method_7454(class_1665.java:371)
	at net.minecraft.class_1676.method_7488(class_1676.java:148)
	at net.minecraft.class_1665.method_5773(class_1665.java:224)
	at net.minecraft.class_1667.method_5773(class_1667.java:104)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_3218$$Lambda$16463/0x00000008032ea3f8.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_3218$$Lambda$16372/0x00000008032c0d28.accept(Unknown Source)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at net.minecraft.server.MinecraftServer$$Lambda$15174/0x00000008030c69c0.run(Unknown Source)
	at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at cyborgcabbage.allarmor.item.ArmorSet.damage(ArmorSet.java:145)
	at net.minecraft.class_1309.handler$zeh000$injected(moriyashiine/bewitchment/mixin/familiar/LivingEntityMixin.java [bewitchment.mixins.json]:239)
	at net.minecraft.class_1309.method_5643(class_1309.java)
	at net.minecraft.class_1657.method_5643(class_1657.java:914)
	at net.minecraft.class_3222.method_5643(class_3222.java:705)
	at net.minecraft.class_1665.method_7454(class_1665.java:371)
	at net.minecraft.class_1676.method_7488(class_1676.java:148)
	at net.minecraft.class_1665.method_5773(class_1665.java:224)
	at net.minecraft.class_1667.method_5773(class_1667.java:104)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_3218$$Lambda$16463/0x00000008032ea3f8.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_3218$$Lambda$16372/0x00000008032c0d28.accept(Unknown Source)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
```

**Comment by CyborgCabbage** [comment]
This bug should be fixed in 1.1.3
